### ISSUE TITLE
React-Native : Unable to resolve module 'fs'

### ISSUE THREAD

**Issue by nayan27** [square/connect-nodejs-sdk#57] opened 2019-07-03 13:21 UTC
Hi,

We want to use the Square-Connect SDK to process payments with the Transactions API. We are currently encountering a problem when attempting to integrate the SquareConnect SDK. To problem seem to be related to the fact that the SDK requires the 'fs' module. I get the following error.

Error: Unable to resolve module `fs` from `C:\Redcandy\Software\React\AreaRN\node_modules\square-connect\src\ApiClient.js`: Module `fs` does not exist in the Haste module map

I replaced the code using fs in ApiClient.js with the following:
`exports.prototype.isFileParam = function(param) {
  // fs.ReadStream in Node.js and Electron (but not in runtime like browserify)
  if (typeof require === 'function') {
    /*var fs;
    try {
      fs = require('fs');
    } catch (err) {}
    if (fs && fs.ReadStream && param instanceof fs.ReadStream) {
      return true;
    }*/
    console.log('Square Connect asked for something we dont know ...');
    return false;
  }
  // Buffer in Node.js
  if (typeof Buffer === 'function' && param instanceof Buffer) {
    return true;
  }
  // Blob in browser
  if (typeof Blob === 'function' && param instanceof Blob) {
    return true;
  }
  // File in browser (it seems File object is also instance of Blob, but keep this for safe)
  if (typeof File === 'function' && param instanceof File) {
    return true;
  }
  return false;
};`

And with that i am able to use the desired Square-Connect SDK features.

What is fs used for ? Would there be a possibility to remove or make the dependancy on fs optionnal so i don't have to make that modification everytime i reset the node_modules of my project ?

Thank you!

Y

**Comment by deanpapastrat** [comment] 2019-08-13 21:00
Some APIs may upload files to Square instead of just posting JSON, which is why the `fs` package  is there. What environment are you using it in? `fs` should be available if you're using the API in a server-side, Node.js context.

**Comment by Pckool** [comment] 2019-08-29 02:42
This happens with Vuejs as well. fs is inside of the node_packages folder and is able to be used in my master js file. But when I try and load this module in a .vue file (separate page files) it spits out that warning.

**Comment by nayan27** [comment] 2019-08-29 13:09
@deanpapastrat Thank you for the reply. Sorry for the late response.

I am using the Square-Connect in React-Native. So my environnment is either Android or iOS. The Square-Connect API is fully functionnal if not for the fs missing error!

**Comment by egeste** [comment] 2019-10-22 21:37
Same

**Comment by StephenJosey** [comment] 2020-01-09 22:18
Hi all - as @deanpapastrat mentioned previously, this SDK is meant to be used server-side only. It's not meant to be used client-side (like Android, iOS, page files in Vue). If it's used client-side, it has potential to expose your private access tokens to anyone using your application. I'm going to go ahead and close this ticket out, as this is intended behavior.

**Closed by StephenJosey** 2020-01-09 22:18 UTC
